spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service-auth
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**

        - id: application-service
          uri: lb://application-service
          predicates:
            - Path=/api/applications/**

        - id: job-service
          uri: lb://job-service
          predicates:
            - Path=/api/jobs/**

        - id: matching-service
          uri: lb://matching-service
          predicates:
            - Path=/api/matching/**

        - id: profile-service
          uri: lb://profile-service
          predicates:
            - Path=/api/profiles/**

        - id: profile-service-singular
          uri: lb://profile-service
          predicates:
            - Path=/api/profile/**

        - id: account-service
          uri: lb://profile-service
          predicates:
            - Path=/api/account/**

        - id: resume-service
          uri: lb://resume-service
          predicates:
            - Path=/api/resumes/**

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
