spring.datasource.url=jdbc:h2:mem:userdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.h2.console.enabled=true
server.port=8081
logging.level.org.hibernate.SQL=ERROR
spring.application.name=user-service
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# JWT Configuration
jwt.secret=MySecretKeyForJWTTokenGeneration1234567890123456789012345678901234567890
jwt.expiration=86400000

